# ───────────────────────────────────────────────────────────────────────────
#  PowerShell 7 profile — zshrc equivalent
#  Generated by bootstrap-win.ps1
# ───────────────────────────────────────────────────────────────────────────

# PSReadLine: history-as-you-type prediction, emacs keys
$script:IsInteractiveConsole = $false
try {
    $script:IsInteractiveConsole = $Host.Name -eq 'ConsoleHost' -and -not [Console]::IsInputRedirected -and -not [Console]::IsOutputRedirected
} catch {
    $script:IsInteractiveConsole = $false
}
if ($script:IsInteractiveConsole -and (Get-Module -ListAvailable PSReadLine)) {
    Import-Module PSReadLine
    Set-PSReadLineOption -EditMode Emacs
    Set-PSReadLineOption -HistorySearchCursorMovesToEnd
    Set-PSReadLineKeyHandler -Key UpArrow   -Function HistorySearchBackward
    Set-PSReadLineKeyHandler -Key DownArrow -Function HistorySearchForward
    Set-PSReadLineKeyHandler -Key Tab       -Function MenuComplete

    try {
        Set-PSReadLineOption -PredictionSource HistoryAndPlugin -ErrorAction Stop
        Set-PSReadLineOption -PredictionViewStyle ListView -ErrorAction Stop
    } catch {
        Set-PSReadLineOption -PredictionSource None -ErrorAction SilentlyContinue
    }
}

# zoxide (smarter cd)
if (Get-Command zoxide -ErrorAction SilentlyContinue) {
    Invoke-Expression (& { (zoxide init powershell | Out-String) })
}

# fzf integration
if (Get-Module -ListAvailable PSFzf) {
    Import-Module PSFzf
    Set-PsFzfOption -PSReadlineChordProvider 'Ctrl+t' -PSReadlineChordReverseHistory 'Ctrl+r'
}

# Icons + git prompt
if (Get-Module -ListAvailable Terminal-Icons) { Import-Module Terminal-Icons }
if (Get-Module -ListAvailable posh-git)       { Import-Module posh-git }

# Aliases — ls -> lsd
if (Get-Command lsd -ErrorAction SilentlyContinue) {
    Remove-Item Alias:ls -Force -ErrorAction SilentlyContinue
    function ls  { lsd @args }
    function ll  { lsd -l @args }
    function la  { lsd -la @args }
    function lt  { lsd --tree @args }
}

# Aliases — bat / cat
if (Get-Command bat -ErrorAction SilentlyContinue) {
    Set-Alias -Name cat -Value bat -Option AllScope -Force -ErrorAction SilentlyContinue
}

# Convenience
function which { param([string]$Name) (Get-Command $Name -ErrorAction SilentlyContinue).Source }
function touch { param([string]$Path) if (-not (Test-Path $Path)) { New-Item -ItemType File -Path $Path | Out-Null } else { (Get-Item $Path).LastWriteTime = Get-Date } }
function .. { Set-Location .. }
function ... { Set-Location ../.. }

# Lazygit
Set-Alias -Name lg -Value lazygit -ErrorAction SilentlyContinue

# Git shortcuts mirroring zshrc habits
function gs { git status @args }
function gd { git diff @args }
function gl { git log --oneline --graph --decorate -20 @args }
function gp { git push @args }
function gpl { git pull @args }
function gco { git checkout @args }
function gcm { git commit -m @args }

# nvm-windows post-install PATH refresh helper
function nvm-refresh {
    $env:PATH = [Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [Environment]::GetEnvironmentVariable('Path','User')
}

# Welcome
if ($script:IsInteractiveConsole) {
    $user = $env:USERNAME
    $host_name = $env:COMPUTERNAME
    Write-Host ""
    Write-Host "  $user@$host_name " -NoNewline -ForegroundColor Cyan
    Write-Host "- $(Get-Date -Format 'yyyy-MM-dd HH:mm')" -ForegroundColor DarkGray
    Write-Host ""
}
